rmk/src/keyboard.rs
This pull request proposes enhancements to the `register_keycode` and `unregister_keycode` functions to improve the readability and clarity.
By using the `iter().position()`, we can directly express the intent of finding an empty slot or a previously registered key, resulting in clearer and more concise code.
=> Improve readability

rmk/src/keyboard.rs
This pull request removes a redundant assignment of `key_state.pressed` to `true` in the `process_key_action_tap` function. The assignment is unnecessary as the condition already checks if the key state is pressed.
=> Remove redundant assignment

rmk/src/debounce.rs, rmk/src/matrix.rs
This pull request refactors the `scan` and `debounce` functions for improved clarity and separation of concerns.
In the original implementation, the `debounce` function handled both debounce logic and updating key states. This mixing of responsibilities could potentially complicate code comprehension and maintenance.
In the refactored code, the `debounce` module exclusively focuses on determining if a state change has occurred, without directly modifying key states. Subsequently, the `matrix` module takes action based on the returned value, thereby clarifying the respective responsibilities of each component and enhancing code understandability.
Additionally, the `debounce` function is renamed to `has_changed` to more accurately reflect its purpose of detecting changes in state, such as …
=> Refactor `scan` and `debounce` functions

rmk/src/debounce.rs
This pull request refactors the `debounce` module.
- Adjusted the visibility of the counter struct.
- Renamed `DebounceState` to `DebounceCounter` to reflect its purpose better.
The rationale behind the name change is to introduce a new enum like this next:
```rust
pub(crate) enum DebounceState {
Debounced,
InProgress,
HeldHigh,
HeldLow,
Ignored,
}
```
The `detect_change_with_debounce` function can return this enum instead of a bool. This adjustment facilitates the reinsertion of held-down keys.
=> Refactor debouncer module

boards/esp32c3_ble/Cargo.lock, boards/nrf52832_ble/Cargo.lock, boards/nrf52840/Cargo.lock, boards/nrf52840_ble/Cargo.lock, boards/rp2040/Cargo.lock, boards/stm32f1/Cargo.lock, boards/stm32f4/Cargo.lock, boards/stm32h7/Cargo.lock, check_all.sh, rmk/Cargo.toml, rmk/src/action.rs, rmk/src/keycode.rs, rmk/src/light.rs, rmk/src/storage.rs, rmk/src/storage/eeconfig.rs, rmk/src/via/keycode_convert.rs
Use `bitfield-struct` to replace`packed_struct`, making it possible to compile for esp32s3
=> Use `bitfield-struct` to replace`packed_struct`, making it possible to compile for esp32s3

rmk/src/keyboard.rs
This pull request aims to improve the behavior of the keyboard events. Currently, the `report.keycodes` is being cleared immediately after sending a report. However, this approach can lead to the loss of the current state of pressed keys, hindering the ability to handle multiple key presses.
The proposed change removes the resetting of `report.keycodes` after sending a report. By retaining the current state of pressed keys until they are released, we ensure that the `report.keycodes` accurately reflects the keyboard's state, enabling better management of key presses and releases.
=> Remove resetting of key states after sending a report

rmk/CHANGELOG.md, rmk/src/keyboard.rs
Currently, modifier bits and keycodes are sent to the keyboard in one report, which leads to the key trigger without the modifier. This PR fixes this by sending modifier first and then sending the key.
This behavior should be identical with qmk's [Modifier Keys](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_advanced_keycodes.md)
=> Fix with_modifier action

rmk/CHANGELOG.md, rmk/src/keyboard.rs, rmk/src/keymap.rs
Similar with #50, sending a capital letter requires to send a shift first, then send the letter.
Also we want to make sure the shift key is sent to host before sending the following key, so we make keyboard task yield after sending the keyboard report to channel.
=> Fix capital letters in macro

README.md
The cargo command no longer works as of 0.24: https://github.com/probe-rs/probe-rs/releases/tag/v0.24.0 This changes it to the installation method featured on the probe.rs site.
=> Update installation method of probe-rs

.vscode/settings.json, docs/src/low_power.md, examples/use_config/esp32c6_ble/Cargo.lock, examples/use_config/stm32h7/src/main.rs, examples/use_rust/esp32c3_ble/src/main.rs, examples/use_rust/esp32c6_ble/src/main.rs, examples/use_rust/esp32s3_ble/src/main.rs, examples/use_rust/hpm5300/src/main.rs, examples/use_rust/nrf52832_ble/src/main.rs, examples/use_rust/nrf52840/src/main.rs, examples/use_rust/nrf52840_ble/src/main.rs, examples/use_rust/rp2040/src/main.rs, examples/use_rust/stm32f1/src/main.rs, examples/use_rust/stm32f4/src/main.rs, examples/use_rust/stm32h7/src/main.rs, examples/use_rust/stm32h7_async/Cargo.lock, examples/use_rust/stm32h7_async/src/main.rs, rmk-macro/CHANGELOG.md, rmk-macro/src/entry.rs, rmk-macro/src/keyboard.rs, rmk/CHANGELOG.md, rmk/Cargo.toml, rmk/src/ble/esp.rs, rmk/src/ble/nrf.rs, rmk/src/lib.rs, rmk/src/split/master.rs, scripts/check_all.sh
Legacy public APIs of RMK are quite complex: `initialize_keyboard_and_run`, `initialize_keyboard_and_run_async_flash`, `initialize_esp_ble_keyboard_with_config_and_run`, `initialize_nrf_ble_keyboard_with_config_and_run`, etc. 
This PR merges them to an unified API `run_rmk` and `run_rmk_with_async_flash`. Different arguments for different chips are enabled by feature gates. This improves the consistency of exposed API, makes APIs easier to use
=> Polish public API

.github/workflows/build esp.yml, .vscode/settings.json, rmk/src/ble/descriptor.rs, rmk/src/ble/esp/server.rs, rmk/src/ble/mod.rs, rmk/src/ble/nrf.rs, rmk/src/ble/nrf/hid_service.rs, rmk/src/ble/nrf/server.rs, rmk/src/ble/nrf/vial_service.rs, rmk/src/keyboard.rs
This PR tries to make vial recognize RMK BLE keyboard. This is currently possible only for Windows because Windows regard BLE HID devices as a normal HID device and use BLE driver automatically.
A successful try is https://github.com/HaoboGu/rmk/pull/70. #70 cannot work with vial-web since vial-web uses report_id 0. 
This PR tries to extract BLE vial service to a separate one and makes vial-web recognize RMK keyboard.
Note: This PR is actually a temporary solution only for Windows. To achieve general vial-over-BLE, the BLE vial service should be a customized service(not HID!). This is because Apple devices don't expose BLE-HID services at all. So, a host tool(like a wireless version of via/vial) needs to be implemented finally.
=> Ble vial service for Windows

rmk/src/ble/nrf.rs, rmk/src/matrix.rs, rmk/src/split/nrf/central.rs, rmk/src/usb/mod.rs
In recent changes, the usb task is started when the BLE is working, this draws about 2mA current. This PR disables usb task for nRF when BLE is working, use softdevice's interrupt to enable USB devices.
Some other optimizations are added as well. As a result, for nRF52840 + high-voltage mode, the advertising current is about 45uA, idle current is about 30uA, and the matrix scanning current is about 1.5mA.
=> Improve nRF power consumption

scripts/check_all.ps1, scripts/format_all.ps1, scripts/release.ps1
I don't think it's necessary to add a Windows GitHub workflow. The current Ubuntu workflow has already proven that the code can be built successfully. And, building `esp-idf-hal` on Windows is not straightforward.
=> feat(script): add powershell scripts

rmk/CHANGELOG.md, rmk/src/ble/esp/mod.rs, rmk/src/ble/nrf/mod.rs, rmk/src/lib.rs, rmk/src/matrix.rs, rmk/src/split/central.rs, rmk/src/split/nrf/central.rs, rmk/src/split/peripheral.rs
Create Debouncer and Matrix in `run_rmk_*` function ahead of time instead of in the `initialize_*_and_run` function.
=> refactor(core): create matrix and debouncer in advance

docs/src/keyboard_configuration.md, rmk-macro/CHANGELOG.md, rmk-macro/src/layout.rs, rmk/CHANGELOG.md, rmk/src/layout_macro.rs
This PR implements the feature discussed in [this issue](https://github.com/HaoboGu/rmk/issues/111).
The "With Modifier" (WM) macro is now supported within the `keyboard.toml` file, allowing users to send a standard keycode with modifier options. 
For example `WM(Kc7, LShift)` would send the keycode `Kc7` with the modifier `LShift`.
=> With modifier support

README.md
It only took me a little over a day from first discovering RMK to flashing [a usable firmware](https://github.com/whitelynx/dactyl-lynx-rmk) complete with a 6-layer keymap created in Vial! I'd like to add my project as a real-world example of RMK being used.
---
I did have to do some hacking to get there, though. First, Vial defaults to only 4 layers, so I had to clone and run it locally, and edit the `DummyKeyboard` class to add more layers. Second, I built [a nice little script](https://github.com/whitelynx/dactyl-lynx-rmk/blob/59afa8307b6e49f315e96898d21b4805bcb55610/scripts/via2rmk.py) to convert from a Vial layout to the `layout.keymap` setting in RMK's `keyboard.toml`. (I'll probably open a PR to upstream that script into RMK itself, since I think others would find it useful)
=> update(README.md): add dactyl-lynx-rmk to real world examples

scripts/via2rmk.py
Added a straightforward script to convert from VIA/Vial layout syntax to RKM's keymap definitions. It can output either a TOML `keymap = [...]` section or a Rust `get_default_keymap()` function.
=> feat(scripts): added via2rmk.py

docs/src/keyboard_configuration.md, rmk-config/src/keyboard_config.rs, rmk-config/src/toml_config.rs, rmk-macro/src/behavior.rs, rmk-macro/src/keyboard.rs, rmk-macro/src/keyboard_config.rs, rmk-macro/src/lib.rs, rmk-macro/src/split/central.rs, rmk/src/ble/esp/mod.rs, rmk/src/ble/nrf/mod.rs, rmk/src/keyboard.rs, rmk/src/keymap.rs, rmk/src/lib.rs, rmk/src/split/central.rs
Closes #143
Implementation will be similar to ZMK, ignore `TriLayerUpper` and `TriLayerLower` key codes and use the layer state instead.
It will be limited to 2 activation layers ("upper" and "lower") and one Tri Layer configuration for now.
=> Tri Layer support

docs/src/keyboard_configuration.md, rmk-config/Cargo.toml, rmk-config/src/keyboard_config.rs, rmk-config/src/toml_config.rs, rmk-macro/src/behavior.rs, rmk-macro/src/keyboard_config.rs, rmk/src/keyboard.rs
Add config under `[behavior]` to customize OSM and OSL timeout.
I believe tap/hold and HRM timeout should wait for #125
=> Add option to customize one shot timeout

examples/use_config/rp2040_direct_pin/keyboard.toml, rmk-macro/src/gpio_config.rs
Support multi "_" GPIO in each row in direct-pins matrix.
Related issue and PR: #140 and #160
=> fix(direct-pins): rust cannot infer the specific type of options for shadowing variables

rmk-macro/src/split/central.rs, rmk-macro/src/split/peripheral.rs
I was facing an inscrutable unwrap error when porting my last-release-compatible keyboard.toml to master.
This commit switches the unwraps for expects that give some more useful diagnostics
=> split: replace unwraps with expect

rmk/src/ble/nrf/mod.rs
I noticed the second setting doesn't take effect since the `set_conn_params` is called before the previous call is finished.
Fixes #100
=> Fix spilt peripheral lag

rmk/src/direct_pin.rs, rmk/src/matrix.rs, rmk/src/split/central.rs
Now the matrix scanning result is sent key processor using `try_send`, which might result in missing key event when typing fast. Changing to async `send` might slow down the scanning rate when the channel is full, but no more missing key.
=> Use async keyboard report sending in matrix scanning

rmk-macro/src/split/peripheral.rs, rmk/src/split/central.rs
Split-direct-keyboard cannot start scanning when some keys are pressed in direct matrix
some futures might skip the `select`
related issue:  #180
=> fix(direct): the size of futs for waiting is incorrect

rmk/src/keycode.rs
`withModifier` get contrary modifier keycode
fixed: #202
=> fix(vial): exchange left and right modifier

.github/workflows/build.yml
- Add determine-runner step, use self-hosted runner or fallback to latest Ubuntu version.
- Remove cargo-bins/cargo-binstall, use cargo install instead.
- Add Python setup step for Python 3.11.
- Add Rust toolchain setup step.
=> ci: Optimize GitHub Actions workflow to use self-hosted runners.

rmk/src/matrix.rs, rmk/src/split/driver.rs, rmk/src/split/nrf/central.rs, rmk/src/split/serial/mod.rs
When connecting splits using serial, there's no way to know the connection state. So after the serial disconnect, peripheral may have wrong connection state.
This PR moves the cached connection state to BLE split message writer, makes serial split driver periodically sync the connection state.
=> Sync connection state periodically when using serial

docs/src/keyboard_configuration.md
=> fix doc typo

rmk/src/keyboard.rs
Allow multi hold-after-tap keys.
Avoid keycode in `KeyboardReport` losing track.
fix: #210
=> fix(tap-hold): unregister keycode properly

.github/workflows/build.yml
- forked branches can't access secrets
need to add the token to the location shown in the figure below
=> ci: github token ref moved from secrets to vars

docs/src/keyboard_configuration.md, rmk-macro/src/layout.rs, rmk/src/layout_macro.rs
This pull request closes issue #221.
I have been able to test the MTH(A,LShift) and it works correctly, but for some reason the TH(X,Y) is not working yet: has it been tested before? I see that Via does not have a binding for the TapHold.
I used all caps for MTH and TH for consistency with the other Layer actions, and i used the ordering <key>, <modifiers> for consistency with WM and LM.
=> Modifier tap hold in keyboard toml

rmk-macro/src/behavior.rs, rmk-macro/src/config/mod.rs
Use the default values defined in `TapHoldConfig` when generating from macros, insted of duplicating the values.
=> fix(macro): use defaults defined in `TapHoldConfig`

scripts/via2rmk.py
Rust output was incorrect compared to examples; this should fix that, and correct/improve the help message a bit.
=> Fix via2rmk Rust output

.github/workflows/build.yml, rmk/src/lib.rs, rmk/src/split/central.rs, rmk/src/split/peripheral.rs
Added `run_rmk_with_async_flash_and_matrix`, `run_rmk_split_central_with_matrix`, and `run_rmk_split_peripheral_with_matrix`.
This will allow keyboards to override matrix scanning, in order to adjust timing, logic levels, etc.
=> feat: added _matrix functions to allow passing custom matrix implementation

rmk/src/ble/nrf/advertise.rs
Right now, running the default setup project for NRF52840 results in adv data which is too large due to the default keyboard name being too long. To avoid this, use `adapt_name` instead of `full_name`.
=> Adapt BLE Advertisement Name

rmk-macro/src/entry.rs, rmk/src/storage/mod.rs
For the first commit, it was discovered that esp-idf-srv::hal::gpio::Output, in fact, does not implement embedded_hal::digital::OutputPin at all. The trait was only implemented for PinDriver.
For the second commit, the iterator returned more keymaps than was defined. The patch was hacky, but it works, review required.
=> Fixed issues that caused compilation to fail on esp32-s3 when using direct pins

rmk-macro/src/behavior.rs, rmk-macro/src/config/mod.rs, rmk-macro/src/keyboard_config.rs, rmk-macro/src/layout.rs, rmk/src/ble/esp/mod.rs, rmk/src/ble/nrf/mod.rs, rmk/src/combo.rs, rmk/src/config/mod.rs, rmk/src/keyboard.rs, rmk/src/keycode.rs, rmk/src/keymap.rs, rmk/src/lib.rs, rmk/src/split/central.rs, rmk/src/storage/mod.rs, rmk/src/via/keycode_convert.rs, rmk/src/via/process.rs, rmk/src/via/vial.rs
=> Combos support

rmk/CHANGELOG.md, rmk/Cargo.toml, rmk/build.rs, rmk/src/lib.rs, rmk/src/storage/mod.rs
=> Add build hash to the storage

examples/use_config/stm32h7/keyboard.toml, rmk-macro/src/config/mod.rs, rmk-macro/src/keyboard_config.rs
This change will detect more `keyboard.toml` mistakes at compile time.
PS
Great job! You have the best default implementation of home row mods
=> Add #[serde(deny_unknown_fields)] to config

rmk/src/ble/esp/server.rs
The serial number string for Esp32 BLE was stored in a characteristic with the wrong UUID 0x2a50 (PnP ID) instead of 0x2A25 (Serial Number String) [see here](https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Assigned_Numbers/out/en/Assigned_Numbers.pdf?v=1740135081988) page 92.
Note: that later in the code your setting the PnP ID, essentially overriding whatever serial number was there anyway
=> Fix esp32 BLE serial number characteristic UUID

.github/workflows/build esp.yml, rmk/Cargo.toml, rmk/src/boot.rs, rmk/src/keyboard.rs, rmk/src/keycode.rs, rmk/src/keymap.rs, rmk/src/lib.rs, rmk/src/via/keycode_convert.rs, rmk/src/via/mod.rs
Add support for Bootloader key (only non-split or central in split support now)
configure in vial: 
- RESET for reset into bootloader
- 0x7c51 for normal reset
related issue: #253
=> feat(boot): jump to Adafruit Nrf52 bootloader

rmk/Cargo.toml, rmk/src/split/rp/uart.rs
Using pio directly instead. Compiles, and works on the central, still haven't gotten the peripheral working.
=> removed pio-proc, as it is an internal use crate.

rmk/src/keycode.rs, rmk/src/keymap.rs, rmk/src/storage/mod.rs, rmk/src/via/vial.rs
hard coded constants replaced to use COMBO_MAX_LENGTH
+ some minor fixes
will be useful if the combo MAX parameters will be part of the config file
=> hard coded constants replaced to use COMBO_MAX_LENGTH

.github/workflows/unit_test.yml, rmk/Cargo.toml, rmk/src/keyboard.rs, rmk/src/via/mod.rs, rmk/src/via/vial.rs
This PR enables unit test for RMK, add several simple unit test for keyboard as demonstration.
Some logging format issue are also fixed to be compatible with both `defmt` and `log`.
=> Configure unit test, add several simple unit test for keyboard

rmk/Cargo.toml, rmk/src/channel.rs, rmk/src/config/mod.rs, rmk/src/input_device/rotary_encoder.rs, rmk/src/keymap.rs, rmk/src/layout_macro.rs, rmk/src/lib.rs, rmk/src/via/mod.rs, rmk/src/via/vial.rs
Hi @HaoboGu,
As https://github.com/HaoboGu/rmk/issues/297, I just added `storage` feature in this PR. Please help me review it
I put it in `default` because I don't want to disrupt other examples that are using `storage`.
To remove the storage feature we just need to change `Cargo.toml`:
```
[dependencies]
rmk = { version = "0.5.2", default-features = false  }
```
Then, in the source, we can go with:
```Rust
// Keyboard config
let rmk_config = RmkConfig {
usb_config: keyboard_usb_config,
vial_config: VialConfig::new(VIAL_KEYBOARD_ID, VIAL_KEYBOARD_DEF),
..Default::default()
};
// Initialize the keymap
let mut default_keymap = keymap::get_default_keymap();
let keymap = initialize_keymap(
&mut default_keymap,
rmk_config.behavior_config.clone(),
)
.await;
// Initialize the matrix + keyboard …
```
=> make the storage as an optional feature and enable by default

rmk/Cargo.toml, rmk/src/split/rp/uart.rs
The rp2040 has weak pull up resistors, from 80k to 50k. This does not provide enough current to provide fast rise times at high baud rates with any moderately high capacitance, even as little capacitance as can be found with long traces, a few vias, or a longer TRRS cable. The solution is to also drive the line high at a weak drive current from the reciving side, providing plenty of current to drive the line high quickly while still being weak enough to be driven low from the tx side.
=> added artificial pull up resistor to pio tx line.

rmk/src/keyboard.rs, rmk/src/keymap.rs, rmk/src/via/vial.rs
This is a simple solution for combo triggering order. Just to make it works.
This PR will prevent early triggering of j+k before j+k+l
=> Sort combo by length desc #302

examples/use_rust/nrf52840_ble/src/main.rs, examples/use_rust/nrf52840_ble_split/src/central.rs, rmk-macro/src/input_device/adc.rs, rmk/src/input_device/adc/nrf.rs
1. Get correct values rather than 0 in the first polling.
2. Replace the type of some integer parameters about time with `Duration`.
=> fix/joystick: optimize the first polling and parameters about duration

rmk-macro/src/behavior.rs, rmk-macro/src/bind_interrupt.rs, rmk-macro/src/chip_init.rs, rmk-macro/src/config/mod.rs, rmk-macro/src/gpio_config.rs, rmk-macro/src/input_device/encoder.rs, rmk-macro/src/keyboard.rs, rmk-macro/src/keyboard_config.rs, rmk-macro/src/layout.rs, rmk-macro/src/matrix.rs
I tried to solve all clippy warnings in the rmk-macro crate.
Some of the adjustments concern the coding style and are a matter of taste.
=> refactor(macro): fix clippy warnings in rmk-macro

docs/en/docs/features/configuration/appendix.md, docs/en/docs/features/configuration/layout.md
Error building the example layout config
error[E0599]: no variant or associated item named `MouseBtn12` found for enum `KeyCode` in the current scope
=> doc(layout): fix mouse key code in the example

rmk/src/keyboard.rs
Currently modifier changed events are only sent together with the HID report, this can cause incorrect behavior for intermediate modifiers that happen between HID reports (one shot, etc.)
=> fix(controller): update modifiers correctly

rmk/Cargo.toml, rmk/src/channel.rs, rmk/src/keyboard.rs, rmk/src/lib.rs
I believe it's a good idea to move controller stuff behind a feature flag since it might increase latency when sending events. We might also want per-event features in the future.
=> feat: move controller behind a feature flag

rmk-config/src/keymap.pest, rmk-config/src/layout.rs
- Changed no_action rule to atomic (@) to capture only "No" without consuming following characters
- Added comprehensive test cases for "No" action parsing
- Ensures "No " (with space) and "No\n" (with newline) are correctly parsed as no_action
- Distinguishes between "No" action and keycodes like "NoUsSlash" or "NonUsSlash"
=> fix: improve pest parser rule to handle "No" action with trailing whitespace

rmk/src/action.rs, rmk/src/keyboard.rs, rmk/src/keymap.rs, rmk/src/layout_macro.rs, rmk/src/via/keycode_convert.rs
Marked this as draft since I'm going to sleep now and haven't had the time to actually test the changes with my layout. 
But I opened the PR to start discussion about 2 things I'm unsure of:
1. the `Action` and `KeyAction` serialization to u16 methods were tricky to update, so I thought I'd comment them out until later. Then I noticed that they were only depended upon by one test case, so I removed them completely in the first commit (I updated the test case to use the enums directly). What is the purpose of the u16 representation? If needed, I can revert the commit and add them back, but I think they would need to be extended to u32. Is there some future plan for these functions, and if so what constraints are there?
2.I hit a snag and realized that the `lm!` macro cannot work with my …
=> move KeyAction::WithModifier to Action::KeyWithModifier

rmk/src/event.rs, rmk/src/input_device/adc/nrf.rs, rmk/src/input_device/battery.rs
These changes aim to improve battery reporting for controllers:
* Report the battery percentage instead of the measured adc value
* Report battery instantly after boot, without waiting for `polling_interval` in `NrfAdc`
=> Battery report changes for controller

rmk/Cargo.toml
This prevented compilation with the `usb_log` feature due to incompatible versions with `embassy-usb`
=> fix: outdated version of `embassy-usb-logger`

rmk-config/src/lib.rs, rmk-macro/src/bind_interrupt.rs, rmk-macro/src/split/peripheral.rs
This PR adds support for configuring the default BLE transmit power (`default_tx_power`) in **rmk** for **nRF-based devices**.
Developers can now optionally set the BLE transmit power via the TOML configuration. If specified, the value is applied during BLE stack initialization. If omitted, the default behavior remains unchanged, ensuring full backward compatibility.
```toml
[ble]
default_tx_power = 8
```
> **Note:**
> This feature is currently implemented only for **nRF** series chips (e.g., `nrf52840`). The field is available for other platforms like **ESP32**, but support has not yet been implemented.
=> Feature:  new BLE option to configuring   default BLE transmit power (default_tx_power)  

docs/en/docs/features/configuration/appendix.md, docs/en/docs/features/configuration/behavior.md, docs/en/docs/features/configuration/layout.md, docs/en/docs/features/configuration/rmk_config.md, examples/use_config/nrf52840_ble_split/keyboard.toml, examples/use_config/rp2040/keyboard.toml, rmk-config/src/behavior.rs, rmk-config/src/keymap.pest, rmk-config/src/layout.rs, rmk-config/src/lib.rs, rmk-macro/src/behavior.rs, rmk/build.rs, rmk/src/action.rs, rmk/src/config/mod.rs, rmk/src/keyboard.rs, rmk/src/keyboard/held_buffer.rs, rmk/src/keyboard/morse.rs, rmk/src/keymap.rs, rmk/src/layout_macro.rs, rmk/src/lib.rs, rmk/src/morse.rs, rmk/src/storage/mod.rs, rmk/src/via/keycode_convert.rs, rmk/src/via/vial.rs, rmk/tests/common/morse.rs, rmk/tests/keyboard_combo_test.rs, rmk/tests/keyboard_morse_hold_on_other_press_test.rs, rmk/tests/keyboard_morse_hrm_test.rs, rmk/tests/keyboard_morse_permissive_hold_test.rs, rmk/tests/keyboard_morse_tap_dance_test.rs
Morse key was introduced in #530, but now the configuration & processing uses tap dance, which is actually different from what the original tap dance means. 
This PR rename `TapDance` to `Morse`, adds documentation that explains the difference between `Morse` and `TapDance`.
`TapHold` is kept as is now, but in the future `TapHold` can also be merged into `Morse` action. That means there's only one kind of multi-role key in RMK world, definitions like `TapHold` and `TapDance` are only a subset of `Morse`. To help the new users, the documentation needs to be polished.
=> Rename `TapDance` to `Morse`

.github/workflows/user_build.yml
In "user_build.yml", wget libssl is too slow, use "action/cache@v4" to speed it up.
Tested here: https://github.com/linrongbin16/rmk-keyboards-nrfmicro/actions/runs/17485812490/job/49664467685
=> ci(libssl): improve libssl installation performance with action/cache@v4

docs/en/docs/features/controller.md, rmk-macro/src/controller/mod.rs, rmk-macro/src/entry.rs, rmk/src/controller/mod.rs
We should allow the user to choose the execution mode of custom controllers defined via `#[controller]`. I propose to change the attribute to be either `#[controller(event)]` or `#[controller(poll)]` so we know what method to call when expanding the controller tasks.
=> Custom controllers execution mode
