README.md, examples/use_config/esp32c3_ble/espflash.toml, examples/use_config/esp32c3_ble/partitions.csv, examples/use_config/esp32c6_ble/espflash.toml, examples/use_config/esp32c6_ble/partitions.csv, examples/use_config/esp32s3_ble/espflash.toml, examples/use_config/esp32s3_ble/partitions.csv, examples/use_rust/esp32c3_ble/espflash.toml, examples/use_rust/esp32c3_ble/partitions.csv, examples/use_rust/esp32c6_ble/Cargo.lock, examples/use_rust/esp32c6_ble/Cargo.toml, examples/use_rust/esp32c6_ble/espflash.toml, examples/use_rust/esp32c6_ble/partitions.csv, examples/use_rust/esp32c6_ble/vial.json, examples/use_rust/esp32s3_ble/espflash.toml, examples/use_rust/esp32s3_ble/partitions.csv, rmk-config/src/keyboard_config.rs, rmk/src/ble/esp.rs, rmk/src/ble/esp/server.rs, rmk/src/hid.rs, rmk/src/keyboard.rs, rmk/src/lib.rs, rmk/src/storage/mod.rs, rmk/src/storage/nor_flash/esp_partition.rs, rmk/src/storage/nor_flash/mod.rs
Last change Also improved full sized keyboard key loading time.
=> Esp32c6 Vial and storage works

rmk/src/keyboard.rs
Related issue: https://github.com/HaoboGu/rmk/issues/71
=> Don't send repeat report when holding the tap/hold key

README.md, README_zh.md
Some content in the README has not been synchronized to the Chinese version.
=> doc: sync english readme to readme_zh line by line

rmk/CHANGELOG.md, rmk/src/ble/nrf/mod.rs, rmk/src/lib.rs
=> Add esp32 restart method

.github/workflows/build_docs.sh, .github/workflows/docs.yml, .gitignore, docs/book.toml, docs/po/zh_CN.po, docs/src/SUMMARY.md, docs/src/documentation_contributing.md, docs/theme/css/language-picker.css, docs/theme/head.hbs, docs/theme/index.hbs
Multilingual builds have been tested and everything seems to be working fine.
You can see the demo here: https://decaday.github.io/rmk/
I also plan to translate the documentation into Simplified Chinese soon.
=> Multilingual documentation preparation

rmk/src/ble/nrf/mod.rs, rmk/src/split/nrf/central.rs, rmk/src/split/peripheral.rs
The conn param is not set for split, which may cause lagging in split peripherals. This PR fixes the issue
=> Fix peripheral lagging

docs/src/keyboard_configuration.md
since those were added in version 0.3.1.
=> Add TO and DF to keyboard_configuration.md

rmk/src/keyboard.rs, rmk/src/keycode.rs, rmk/src/layout_macro.rs
=> One-shot key support

docs/theme/index.hbs
mdBook v0.4.41 updated the index.hbs:
https://github.com/rust-lang/mdBook/blob/90960126e8b2da1dc1a7e460c2bdeb8073f1b81e/CHANGELOG.md?plain=1#L11-L14
Refs #133
=> Fix broken documentation links

docs/src/keyboard_configuration.md, rmk-macro/src/layout.rs
Add option to set OSM key in the `keyboard.toml` file. (forgot to do this in the other pr 🙃)
=> Config option for OSM

docs/src/faq.md, docs/src/storage.md, examples/use_config/nrf52840_ble/keyboard.toml, examples/use_rust/nrf52832_ble/src/main.rs, examples/use_rust/nrf52840_ble/src/main.rs, examples/use_rust/nrf52840_ble_split/src/central.rs, rmk-macro/CHANGELOG.md, rmk-macro/src/config/mod.rs, rmk-macro/src/default_config/esp32.rs, rmk-macro/src/default_config/nrf52810.rs, rmk-macro/src/default_config/nrf52832.rs, rmk-macro/src/default_config/nrf52840.rs, rmk-macro/src/default_config/rp2040.rs, rmk-macro/src/default_config/stm32.rs, rmk-macro/src/flash.rs, rmk-macro/src/keyboard_config.rs, rmk/CHANGELOG.md, rmk/src/ble/esp/mod.rs, rmk/src/config/mod.rs, rmk/src/storage/mod.rs
=> feat(storage): add `clear_storage` option

rmk/CHANGELOG.md, rmk/src/direct_pin.rs, rmk/src/split/central.rs, rmk/src/split/peripheral.rs
Closes #171 
Direct pin doesn't need to be affected by `col2row` feature. This PR removes it as well.
=> Fix direct pin matrix size error

rmk/src/ble/esp/mod.rs, rmk/src/ble/mod.rs, rmk/src/ble/nrf/bonder.rs, rmk/src/ble/nrf/mod.rs, rmk/src/ble/nrf/server.rs, rmk/src/keyboard.rs, rmk/src/lib.rs, rmk/src/matrix.rs, rmk/src/split/driver.rs, rmk/src/split/mod.rs, rmk/src/split/nrf/central.rs, rmk/src/split/nrf/peripheral.rs, rmk/src/split/peripheral.rs, rmk/src/split/serial/mod.rs, rmk/src/usb/mod.rs
`CONNECTION_STATE` is added to indicate whether the host is connected. If the host is not connected, just don't send any message.
Closes #187
Closes #186
=> Add connection state checking

.github/workflows/build.yml
- Change stm32f1 build command from `cargo build --release` to `cargo make uf2 --release`
=> ci: fix stm32f1 build command:

docs/po/zh_CN.po, docs/src/user_guide/2-2_local_compilation.md
I've changed some phrasing in the local compilation part of the docs to (hopefully) improve legibility.
Feel free to provide feedback or request further changes.
=> chore: update language of local compilation doc

rmk-macro/src/keyboard_config.rs
Fixes the check if either board or chip is set in config.
=> fix(config) check if either board or chip is set

rmk/src/debounce/default_bouncer.rs, rmk/src/debounce/fast_debouncer.rs, rmk/src/hid.rs, rmk/src/input_device/rotary_encoder.rs, rmk/src/keyboard.rs, rmk/src/keycode.rs, rmk/src/storage/mod.rs
Fix in mouse_report button release: &= 0b0111, like bit patterns were wrong (0b11110111 is correct), fixed in nicer format: !(1 << 3)
Likely fix in default_debouncer: I guess the elapsed_ms should be added not 1
small optimizations 
small typo fixes
=> minor fixes

examples/use_config/rp2040/Cargo.toml, examples/use_config/rp2040_direct_pin/Cargo.toml, examples/use_config/rp2040_split/Cargo.toml, examples/use_config/rp2040_split_pio/Cargo.toml, examples/use_rust/rp2040/Cargo.toml, examples/use_rust/rp2040_direct_pin/Cargo.toml, examples/use_rust/rp2040_split/Cargo.toml, examples/use_rust/rp2040_split_pio/Cargo.toml, examples/use_rust/rp2350/Cargo.toml, rmk/Cargo.toml, rmk/src/boot.rs
=> Jump to bootloader key for rp2040

docs/src/keyboard_configuration.md, rmk-macro/src/layout.rs, rmk/src/layout_macro.rs
=> Add `shifted!` macro and `SHIFTED` key in config

docs/src/keyboard_configuration.md, rmk-macro/src/layout.rs, rmk/src/keyboard.rs, rmk/src/keymap.rs, scripts/via2rmk.py
=> feat(toml): add `KeyAction::Transparent` to keyboard.toml

docs/src/keyboard_configuration.md, docs/src/vial_support.md
Improvements to the documentation taken from the discussion in #304
=> doc improvements, explaining relation to vial and input/output pins

docs/src/input_devices/encoder.md, examples/use_rust/nrf52840_ble/src/main.rs, examples/use_rust/nrf52840_ble_split/src/central.rs, rmk-macro/src/config/mod.rs, rmk-macro/src/gpio_config.rs, rmk-macro/src/input_device/encoder.rs, rmk-macro/src/input_device/mod.rs
=> Add toml config and documentation for encoders

examples/use_rust/py32f07x/Cargo.lock, examples/use_rust/stm32g4/Cargo.lock, rmk/Cargo.toml, rmk/src/combo.rs, rmk/src/keyboard.rs
1. combo triggers order by lengh desc
2. fix multi combo triggers
=> fixbug #302 combo combination; part 1 , combo status issue

examples/use_config/nrf52840_ble_split/src/central.rs, examples/use_config/nrf52840_ble_split_direct_pin/src/central.rs, examples/use_config/rp2040_split/src/central.rs, examples/use_config/rp2040_split/src/peripheral.rs, examples/use_config/rp2040_split_pio/src/central.rs, examples/use_config/rp2040_split_pio/src/peripheral.rs
Fix some minor typo in examples.
=> chore: fix typo

docs/src/keyboard_configuration.md, rmk-macro/Cargo.toml, rmk-macro/src/config/mod.rs, rmk-macro/src/keyboard_config.rs, rmk-macro/src/keymap.pest
Available for testing! Updated keyboard configuration documentation is included.
=> Introduce matrix map for nicer configs

docs/src/keyboard_configuration.md
The important fix is in line 236.
=> documentation formatting fixes

rmk-macro/src/chip_init.rs, rmk/src/ble/trouble/mod.rs, rmk/src/input_device/adc/nrf.rs, rmk/src/input_device/battery.rs
=> Add sleep for advertising

rmk/CHANGELOG.md, rmk/Cargo.toml, rmk/src/light.rs
and adjust default trouble pool size
=> Fix capslock stuck on macOS

examples/use_rust/nrf52840_ble_split/src/peripheral.rs
=> Use ble_addr in nrf split peripheral clear_storage

docs/src/user_guide/2-2_local_compilation.md
I'm reading the documentation in the hope of flashing and customizing a keyboard - do you want documentation PR(s) with small fixe(s) as I encounter stuff? Would you prefer me just combining it in this PR, and marking it ready once I think I'm done reading documentation for now?
=> docs(user_guide): grammar

docs/.vitepress/theme/custom.css, docs/README.md, docs/en/index.md
- Add scrollbar styles
- update README.md
- update github link styles
=> docs: Add scrollbar styles and update documentation

docs/.vitepress/theme/custom.css, docs/.vitepress/theme/custom.scss, docs/en/docs/features/configuration/keyboard_matrix.md, docs/en/docs/features/configuration/layout.md, docs/en/docs/features/storage.md, docs/en/docs/features/vial_support.md, docs/en/docs/input_devices/joystick.md
docs: adjust font size scaling for better readability and add warning block styles
=> docs: adjust font size scaling for better readability and add warning block styles

docs/.vitepress/config.mts, docs/.vitepress/theme/custom-block-style.scss, docs/.vitepress/theme/custom.css, docs/.vitepress/theme/custom.scss, docs/en/docs/custom-block-ex.md
docs: Improve the style of the code block and update the style of the custom block
=> docs: Improve the style of the code block and update the style of the custom block

docs/.vitepress/config.mts
=> docs(vitepress): enable deep heading outlining and simplify config

docs/en/docs/device.md, rmk-macro/src/keyboard.rs, rmk/CHANGELOG.md, rmk/src/boot.rs, rmk/src/channel.rs, rmk/src/lib.rs, rmk/src/storage/mod.rs
.. and remove some outdated todos
=> Save only used macro space to storage

examples/use_config/nrf52840_ble_split/keyboard.toml, rmk-config/src/behavior.rs, rmk-config/src/lib.rs, rmk-macro/src/behavior.rs, rmk/build.rs, rmk/src/config/mod.rs, rmk/src/lib.rs, rmk/src/tap_dance.rs
maybe another name should be used, it's not the "real" tap-dance
=> Add configurations for tap-dance

rmk/src/split/serial/mod.rs
=> Fix occasional repeat message from peripheral

rmk/src/combo.rs, rmk/src/keyboard.rs, rmk/tests/common/mod.rs, rmk/tests/keyboard_combo_test.rs, rmk/tests/keyboard_one_shot_test.rs
Fixes #453 
Add integrated tests for combo and one-shot keys
=> Fix combo + one shot issue

rmk/src/ble/trouble/battery_service.rs, rmk/src/keyboard.rs
Signed-off-by: Haobo Gu <haobogu@outlook.com>
=> Report battery level only when there's a key action recently

rmk/src/keyboard.rs, rmk/src/keycode.rs, rmk/src/via/keycode_convert.rs, rmk/src/via/vial.rs
=> Add capsword support

docs/en/docs/features/configuration/behavior.md, examples/use_rust/esp32s3_ble/src/main.rs, examples/use_rust/nrf52832_ble/src/main.rs, examples/use_rust/nrf52840_ble/src/main.rs, examples/use_rust/nrf52840_ble_split/src/central.rs, examples/use_rust/pi_pico_w_ble/src/main.rs, rmk-config/src/lib.rs, rmk-macro/src/behavior.rs, rmk/src/action.rs, rmk/src/keyboard/held_buffer.rs, rmk/src/keyboard/morse.rs, rmk/src/keycode.rs, rmk/src/storage/mod.rs, rmk/src/tap_dance.rs, rmk/src/via/vial.rs, rmk/tests/common/morse.rs, rmk/tests/keyboard_morse_tap_dance_test.rs
=> Remove strict mode for tap-dances, use exactly match instead
